Update sixlabors 3.0.1
vnbaaij/Baaijte.Optimizely.ImageSharp.Web pull request #21
Opened 2023-08-18 12:14 UTC by AlexanderSeel

# Pull Request

## 📖 Description

### 🎫 Issues

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

## ✅ Checklist

### General

- [x ] I have added tests for my changes.
- [x ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component

## ⏭ Next Steps

2023-08-18 14:02 UTC, vnbaaij requested changes

2023-08-18 14:02 UTC, vnbaaij commented on src/Baaijte.Optimizely.ImageSharp.Web/Baaijte.Optimizely.ImageSharp.Web.csproj
Happy to name you as a contributor, but not going to mark you as author and repo

2023-08-18 14:02 UTC, vnbaaij commented on src/Baaijte.Optimizely.ImageSharp.Web/Baaijte.Optimizely.ImageSharp.Web.nuspec
Same remarks, don't change author/owner/repo links

2023-08-22 07:12 UTC, AlexanderSeel commented on src/Baaijte.Optimizely.ImageSharp.Web/Baaijte.Optimizely.ImageSharp.Web.csproj
Oh sorry this was not intentional

2023-08-22 07:17 UTC, AlexanderSeel commented on src/Baaijte.Optimizely.ImageSharp.Web/Baaijte.Optimizely.ImageSharp.Web.csproj
Hi, can you give me a hint, I just don't want to be the owner. Which checkmark I missed. Kind gerads

2023-08-22 07:22 UTC, AlexanderSeel reviewed
changed project url, author and owner

2023-08-22 07:27 UTC, vnbaaij approved these changes

2023-08-22 07:29 UTC, merged